# Generated by Django 5.2.6 on 2026-01-23 14:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('network_address', models.GenericIPAddressField(protocol='IPv4')),
                ('prefix', models.PositiveSmallIntegerField()),
                ('description', models.CharField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4')),
                ('status', models.IntegerField(choices=[(1, 'used'), (2, 'free')], default=2)),
                ('description', models.CharField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('netowrk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ipam.network')),
            ],
        ),
    ]
