# Generated by Django 5.2.8 on 2026-02-05 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('network_address', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('prefix', models.PositiveSmallIntegerField(choices=[(8, '/8'), (9, '/9'), (10, '/10'), (11, '/11'), (12, '/12'), (13, '/13'), (14, '/14'), (15, '/15'), (16, '/16'), (17, '/17'), (18, '/18'), (19, '/19'), (20, '/20'), (21, '/21'), (22, '/22'), (23, '/23'), (24, '/24'), (25, '/25'), (26, '/26'), (27, '/27'), (28, '/28'), (29, '/29'), (30, '/30')])),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('status', models.IntegerField(choices=[(1, 'used'), (2, 'free')], default=2)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_addresses', to='ipam.network')),
            ],
        ),
    ]
