# Generated by Django 5.2.6 on 2026-01-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='prefix',
            field=models.PositiveSmallIntegerField(choices=[(8, '/8'), (9, '/9'), (10, '/10'), (11, '/11'), (12, '/12'), (13, '/13'), (14, '/14'), (15, '/15'), (16, '/16'), (17, '/17'), (18, '/18'), (19, '/19'), (20, '/20'), (21, '/21'), (22, '/22'), (23, '/23'), (24, '/24'), (25, '/25'), (26, '/26'), (27, '/27'), (28, '/28'), (29, '/29'), (30, '/30')]),
        ),
    ]
