# Generated by Django 5.2.6 on 2026-01-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0002_alter_network_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='ip_address',
            field=models.GenericIPAddressField(protocol='IPv4', unique=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='network_address',
            field=models.GenericIPAddressField(protocol='IPv4', unique=True),
        ),
    ]
