# Generated by Django 5.2.6 on 2026-01-24 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0003_alter_ipaddress_ip_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipaddress',
            old_name='netowrk',
            new_name='network',
        ),
    ]
