# Generated by Django 5.2.6 on 2026-01-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0004_rename_netowrk_ipaddress_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
