# Generated by Django 5.2.6 on 2026-01-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0005_ipaddress_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
