# Generated by Django 5.2.6 on 2026-01-24 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0006_alter_ipaddress_created_at_alter_network_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipaddress',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipam.network'),
        ),
    ]
