# Generated by Django 5.2.6 on 2026-01-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0007_alter_ipaddress_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='network',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
